--- 
abstract: Perl interface to Backlog.
author: Ryuzo Yamamoto <yamamoto@nulab.co.jp>
build_requires: 
  Encode: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: WebService-Backlog
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Class::Accessor::Fast: 0
  RPC::XML: 0
version: 0.01_01
